[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "..\\common" }
eframe = { version = "0.28.1", features = ["wgpu"] }
wgpu = { version = "0.20.1", default-features = true }
